name: Security Scans (Frontend)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sast:
    uses: ./.github/workflows/sast-frontend.yml

  sca:
    uses: ./.github/workflows/sca-frontend.yml

  container:
    uses: ./.github/workflows/container-security-frontend.yml
